### ISSUE TITLE
Convert to Python3

### ISSUE THREAD

**Issue by krzk** [linux-nfc/neard#3]
Convert the Python test scripts to Python3.

**Comment by cc-michaelu** [comment]
I have opened a PR containing the conversion of the Python 2 scripts to Python 3. Please try these patches.

**Comment by jtojnar** [comment]
Note that there is already some work in https://github.com/linux-nfc/neard/commits/mag/python3-ize branch.

**Comment by cc-michaelu** [comment]
> Note that there is already some work in https://github.com/linux-nfc/neard/commits/mag/python3-ize branch and the mailing lists.

I did not see that branch, looks like similar to what I submitted. Why didn't you submit a PR for those changes?

**Comment by jtojnar** [comment]
Mark submitted it for review on the [mailing list](https://lore.kernel.org/linux-nfc/20210808022058.171350-1-mgreer@animalcreek.com/), no point in sending it to two places at the same time.

**Comment by cc-michaelu** [comment]
Should I close my PR then?

I will keep it on my fork...

**Comment by jtojnar** [comment]
You can try to rebase your changes onto the branch and target it like https://github.com/linux-nfc/neard/pull/13 does.

**Comment by cc-michaelu** [comment]
It is not an easy merge due to differences in formatting. I ran the scripts through `blank` formatter which results in a different format from what is on the `python3-ize` branch. So I think I will be closing my PR.

The quick eyeball of the conflicts indicate what is on the branch is virtually identical (aside from formatting) to the code in my branch. I will keep my fork for my own work going forward (as we are using `neard` in our device).
